{% set name = "tenacity" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tenacity-{{ version }}.tar.gz
  sha256: 807f37ca97d62aa361264d497b0e31e92b8027044942bfa756160d908320d73b

build:
  number: 1
  script: {{ PYTHON }} -m pip install -vv .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=21.0.0,!=24.0.0,!=34.0.0,!=34.0.1,!=34.0.2,!=34.0.3,!=34.1.0,!=34.1.1,!=34.2.0,!=34.3.0,!=34.3.1,!=34.3.2,!=36.2.0
    - setuptools-scm >=3.4
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - tenacity

about:
  home: http://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works

  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  doc_url: http://tenacity.readthedocs.io
  dev_url: http://github.com/jd/tenacity

extra:
  recipe-maintainers:
    - sodre
    - xylar
