schema_version: 1

context:
  name: tenacity
  version: "9.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tenacity-${{ version }}.tar.gz
  sha256: a606b5c808d0cded4a359d5b9932d867ff2a6a6b64d37350260fd01bbdf83839

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tenacity
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works
  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  homepage: http://github.com/jd/tenacity
  repository: http://github.com/jd/tenacity
  documentation: http://tenacity.readthedocs.io

extra:
  recipe-maintainers:
    - sodre
    - xylar
