schema_version: 1

context:
  name: tenacity
  version: "9.1.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/tenacity-${{ version }}.tar.gz
  sha256: adb31d4c263f2bd041081ab33b498309a57c77f9acf2db65aadf0898179cf93a

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=21.0.0,!=24.0.0,!=34.0.0,!=34.0.1,!=34.0.2,!=34.0.3,!=34.1.0,!=34.1.1,!=34.2.0,!=34.3.0,!=34.3.1,!=34.3.2,!=36.2.0
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - tenacity
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works
  description: |
    Tenacity is general-purpose retrying library, written in Python, to simplify the task of
    adding retry behavior to just about anything. It originates from a fork of Retrying
  homepage: http://github.com/jd/tenacity
  repository: http://github.com/jd/tenacity
  documentation: http://tenacity.readthedocs.io

extra:
  recipe-maintainers:
    - sodre
    - xylar
